#!/bin/bash
set -a
source ~/.config/bspwm/.env
set +a

pgrep -x sxhkd > /dev/null || sxhkd &

[[ "$DEVICE" = "PC" ]] && xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 75.00 --output DVI-D-0 --mode 1280x1024 --rate 75.00 --right-of HDMI-0 --output DP-1 --mode 1280x1024 --rate 75.00 --left-of HDMI-0 &
xrandr --dpi 81 &
bash ~/.fehbg &
wmname LG3D &
picom &
dunst &
alttab -w 1 -d 2 -bg "#1c1c1c" -fg "#b5b4c9" -frame "#b5b4c9" -font "xft:SometypeMono-12" &
greenclip daemon &
lxpolkit &
nvidia-settings --load-config-only &
xset m 0 0 &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

[[ "$DEVICE" = "LT" ]] && bspc monitor eDP1 -d 1 2 3 4 5

if [[ "${DEVICE}" = "PC" ]]; then
    bspc monitor DP-1 -d 1 2 3
    bspc monitor HDMI-0 -d 4 5 6 7
    bspc monitor DVI-D-0 -d 8 9 10
fi

bspc config border_width          0
bspc config window_gap            6
bspc config top_padding 	      24

bspc config split_ratio           0.55

bspc config normal_border_color   '#1c1c1c'
bspc config active_border_color   '#1c1c1c'
bspc config focused_border_color  '#1c1c1c'

if [[ "$DEVICE" = "PC" ]]; then
    bspc rule -a discord desktop=8
    bspc rule -a thunderbird desktop=1
    bspc rule -a kitty desktop=4
fi

# launch stuff
[[ "$DEVICE" = "PC" ]] && sh $HOME/.config/bspwm/launchStuff.sh
