#!/bin/bash
set -a
source ~/.config/bspwm/.env
set +a

pgrep -x sxhkd > /dev/null || sxhkd &

[[ "$DEVICE" = "PC" ]] && xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 75.00 --output DisplayPort-1 --mode 1280x1024 --rate 75.00 --right-of DisplayPort-0 --output DisplayPort-2 --mode 1280x1024 --rate 75.00 --left-of DisplayPort-0 &
xrandr --dpi 81 &
bash ~/.fehbg &
# wmname LG3D &
picom &
dunst &
alttab -w 1 -d 2 -bg "#1c1c1c" -fg "#b5b4c9" -frame "#b5b4c9" -font "xft:SometypeMono-12" &
greenclip daemon &
lxpolkit &
xset m 0 0 &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

# Setting up bspwm desktops
[[ "$DEVICE" = "LT" ]] && bspc monitor eDP1 -d 1 2 3 4 5

if [[ "${DEVICE}" = "PC" ]]; then
    bspc monitor DisplayPort-2 -d 1 2 3
    bspc monitor DisplayPort-0 -d 4 5 6 7
    bspc monitor DisplayPort-1 -d 8 9 10
fi

# bspwm styling
bspc config border_width          0
bspc config window_gap            6
bspc config top_padding           24

bspc config split_ratio           0.55

bspc config normal_border_color   '#1c1c1c'
bspc config active_border_color   '#1c1c1c'
bspc config focused_border_color  '#1c1c1c'

# setting desktops for autostarts
if [[ "$DEVICE" = "PC" ]]; then
    bspc rule -a discord desktop=8
    bspc rule -a thunderbird desktop=1
#    bspc rule -a kitty desktop=4
fi

# autostart
[[ "$DEVICE" = "PC" ]] && sh $HOME/.config/bspwm/autostart.sh
