add_newline = true

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[✗](bold red) "

[hostname]
disabled = true

[directory]
style = "blue"
read_only = ""
truncation_symbol = ".../"
truncation_length = 5

[username]
style_user = "green"
disabled = true

[memory_usage]
disabled = false
threshold = 90

[cmd_duration]
disabled = true

[package]
disabled = true

[jobs]
disabled = true

[localip]                          
disabled = true

[container]
disabled = true
